csv_gen/urls.py
from django.contrib import admin
from django.urls import path,include
from csvapp.views import export_csv,home,upload_csv
from csvapp.views import ContactView, ContactSuccessView

# app_name = 'contact'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/',home,name='home'),
    path('export-csv/',export_csv,name='csv'),
    path('upload_csv',upload_csv,name='upload_csv'),
    path('', include('csvapp.urls'))
    # path('',ContactView.as_view(),name='contact'),
    # path('success/',ContactSuccessView.as_view(),name='success'),

]

csvapp/urls.py
from django.urls import path
from .views import ContactView, ContactSuccessView

app_name = 'csvapp'

urlpatterns = [
    path('', ContactView.as_view(), name="contact"),
    path('success/', ContactSuccessView.as_view(), name="success"),
]

csvapp/models.py
from django.db import models

# Create your models here.


class Csv_emp(models.Model):
    name = models.CharField(max_length = 100) 
    company = models.CharField(max_length = 100)
    salary = models.IntegerField()
    designation = models.CharField(max_length = 100)
    DOJ = models.DateTimeField(auto_now_add = True)
    active = models.BooleanField(default = True)

    def __str__(self):
        return f'{self.name}---------{self.company}'
    
    class Meta:
        db_table = 'emp'


class Employee(models.Model):
    Emp_Name = models.CharField(max_length=200)
    Emp_Salary = models.IntegerField()
    is_boolean = models.BooleanField(default=True)
    Emp_company = models.CharField(max_length=200)

    
    def __str__(self):
        return f"{self.Emp_Name} -- {self.Emp_company}"

    class Meta:
        db_table = "empl"


    def create_employee():
        emp = Employee(Emp_name='Rakesh', Emp_Salary=35000, Emp_company="Accenture")
        emp.save()
        return emp














    # def delete(self,*args,**kwargs):
    #     self.pdf.delete()
    #     self.cover.delete()
    #     super().delete(*args,**kwargs)

    

csvapp/forms.py
from django import forms
from django.conf import settings
from django.core.mail import send_mail

class ContactForm(forms.Form):
    name = forms.CharField(max_length=100)
    email = forms.EmailField()
    inquiry = forms.CharField(max_length=70)
    message = forms.CharField(widget=forms.Textarea)

    def get_info(self):
        """Method that returns formatted information
        :return: subject, msg"""
        cl_data = super().clean()  #cleaned data

        name = cl_data.get('name').strip()
        from_email =cl_data.get('email')
        subject = cl_data.get('inquiry')

        msg = f'{name} with email {from_email} said:'
        msg += f'\n"{subject}"\n\n'
        msg += cl_data.get('message')

        return subject, msg

    def send(self):
        subject, msg = self.get_info()

        send_mail(
            subject=subject,
            message=msg,
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[settings.RECIPIENT_ADDRESS]
        )




# from django import forms
# from csvapp.models import Csv_book

# class Bookform(forms.ModelForm):
#     class Meta:
#         model = Csv_book
#         fields = '__all__'

csvapp/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse,HttpResponseRedirect
from django.urls import reverse
from csvapp.models import Csv_emp
import csv
from django.views.generic import FormView, TemplateView
from .forms import ContactForm
from django.urls import reverse_lazy

# Create your views here.

def home(request):
    return render(request, template_name='home.html')


def export_csv(request):
    all_active = Csv_emp.objects.filter(active = True)
    response = HttpResponse(content_type = 'csv/txt')
    csv_writer = csv.writer(response)
    csv_writer.writerow(["ID", "Name", "Salary", "Company",
                        "Designation", "DOJ", "Active"])
    

    for emp in all_active.values_list('id','name','company','salary','designation','DOJ','active'):
        csv_writer.writerow(emp)
    
    response['Content-Disposition'] = 'attachment; filename = "employee-data.csv"'
    return response

def upload_csv(request):
    data ={}
    if "GET" == request.method:
        return render(request,'upload.html',data)
    try:
        csv_file = request.FILES['csv_file']
        if not csv_file.name.endswith('.csv'):
            return HttpResponseRedirect(reverse("upload_csv"))

        if csv_file.multiple_chunks():
            return HttpResponseRedirect(reverse("upload_csv"))

        file_data = csv_file.read().decode('utf-8')

    except Exception as e:
        print(e)

    return HttpResponseRedirect(reverse("upload_csv"))


class ContactView(FormView):
    template_name = 'contact.html'
    form_class = ContactForm
    success_url = reverse_lazy('csvapp:success')

    def form_valid(self,form):
        form.send()
        return super().form_valid(form)

# function based view
# if request.method == 'POST':
#     form = ContactForm(request.POST)
#     if form.is_valid():
#         form.send()
#         return redirect('contact:success')
# else:
#     form = ContactForm())

class ContactSuccessView(TemplateView):
    template_name = 'success.html'


























# def upload(request):
#     context = {}
#     if request.method == 'POST':
#         upl_file = request.FILES['document']
#         fs = FileSystemStorage()
#         name = fs.save(upl_file.name,upl_file)
#         print(name,fs.url(name))
#         context['url'] = fs.url(name)
#     return render(request,'upload.html',context)

# def all_books(request):
#     books = Csv_book.objects.all()
#     return render(request,'all_books.html',{'all_books':books})

csvapp/templates/base.html
<html lang="en">

  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Django Email Send</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous" />
  </head>

  <body>
    {% block body %}

    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8" crossorigin="anonymous">
    </script>
  </body>

</html>

csvapp/templates/contact.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block body %}
<div class="mx-auto my-4 text-center">
    <h1>Contact Us</h1>
</div>
<div class="container">
    <form action="" method="post">
        {% csrf_token %}
        {{ form | crispy }}
    <button class="btn btn-success my-3" type="submit">Send message</button>
    </form>
</div>
{% endblock %}

csvapp/templates/home.html
<html>
    <head>
        <title>Home</title>
    </head>
    <body bgcolor="green" >
        <h1>Django CSV File Generator</h1>
        <br> 
        <table border="2" style="width: 50%;">
            <thead>
                <tr>
                    <th>Download CSV</th>
                    <th>Download</th>
                </tr>
            </thead>
            <tr>
                <td>
                    All Employees Details
                </td>
                <td>
                <form action="{% url 'csv' %}">
                    {% csrf_token %} 
                    <input type="submit" value="Download" >
                    </form>
                </td>
            </tr>
        </table>
        <br><br>

        <a href="{% url 'upload_csv' %}"><strong>Upload CSV</strong></a>
    </body>
</html>

csvapp/templates/success.html
{% extends 'base.html' %}

{% block body %}
<div class="mx-auto my-4 text-center">
    <h1 class="fw-bolder text-success">We sent your message</h1>
    <p class="my-5">You can send another in the <a href="{% url 'csvapp:contact' %}">contact page</a></p>
</div>
{% endblock %}

csvapp/templates/upload.html
<html>
    <body bgcolor="green">

<form action='{% url "upload_csv" %}'' method="POST" enctype="multipart/form-data" class="form-horizontal"> 
    {% csrf_token %}
    <div class="form-group">
        <label for="name" class="col-md-3 col-sm-3 col-xs-12 control-label">File: </label><br><br>
        <div class="col-md-8">
            <input type="file" name="csv_file" id="csv_file" required="True" class="form-control"><br><br>
        </div>                    
    </div>
    <div class="form-group">                    
        <div class="col-md-3 col-sm-3 col-xs-12 col-md-offset-3" style="margin-bottom:10px;">
             <button class="btn btn-primary"> <span class="glyphicon glyphicon-upload" style="margin-right:5px;"></span>Upload </button>
             
            </div> 

    </div>
  
    </form>
    
</body>